apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/francdomain/py-greet.git
    targetRevision: HEAD
    path: argocd/python-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: {}
