## MOVE THIS FILE to `.github/workflows/docker-build.yaml` TO EXECUTE IT

name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 # Updated version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Updated version

      - name: Login to DockerHub
        uses: docker/login-action@v2 # Updated version
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4 # Updated version
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: francdocmain/python-helloworld:latest